### ISSUE TITLE
Base64 Images

### ISSUE THREAD

**Issue by ChrisButterworth** [mklement0/fileicon#10]
Could base64 encoded images be used?

**Comment by mklement0** [comment]
`fileicon` supports the [image formats natively supported by Cocoa](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/CocoaDrawingGuide/Images/Images.html#//apple_ref/doc/uid/TP40003290-CH208-BCIIFBJG); base64-encoded data is therefore _not_ supported.

However, you can use the `base64` utility to decode your data and use something like the following:

```bash
base64 -D base64-image-file.txt > image-file
fileicon set some-folder image-file
```
