### ISSUE TITLE
Add option to set image icon to file's self

### ISSUE THREAD

**Issue by astout** [mklement0/fileicon#11]
Thanks for this utility by the way. I was taken back by the deprecation of `sips -i` in macOS 10.13 and found your utility to fulfill my needs.

That said I would like to suggest a minor improvement. Either add another command like:

`fileicon setself icon.png`

OR modify the `set` command to allow a single argument. The default behavior of a single parameter would be just like `sips -i` where the image file icon is set to the content of the image file itself. i.e.

` fileicon set icon.png`

Honestly this is just out of sheer laziness. I'd prefer not to provide the same path twice ;).

**Comment by mklement0** [comment]
Your laziness is my command 😉 

I've just published v0.2.2 to the npm registry, which now does what you want.

**Comment by astout** [comment]
@mklement0: You, sir, are a gentleman and a scholar. Thanks for the update!
