### ISSUE TITLE
Homebrew formula?

### ISSUE THREAD

**Issue by danielbayley** [mklement0/fileicon#13]
@mklement0 I have a working [Homebrew formula](https://docs.brew.sh/Formula-Cookbook) for this project locally in my dotfiles… but maybe it should live with the project creator? So here it is if you want to include it somewhere:

~~~ rb
class Fileicon < Formula
  desc "macOS CLI for managing custom icons for files and folders"
  homepage "https://github.com/mklement0/fileicon"
  url "https://github.com/mklement0/fileicon/archive/v0.2.2.tar.gz"
  sha256 "1725a6a693b3586617b0fc669719a15c05eb7f8e535daee511a315d9b6fc0eb3"

  def install
    bin.install "bin/fileicon"
    man1.install "man/fileicon.1"
  end

  test do
    stdout = shell_output "#{bin}/fileicon --version"
    assert_match /fileicon v#{version}/, stdout
  end
end
~~~

**Comment by mklement0** [comment]
Thank you, @danielbayley, I appreciate it. I'll look into submitting this as an official formula.

**Comment by danielbayley** [comment]
@mklement0 I don't think this repo has enough watching/stars/forks yet for their minimum acceptable formula requirements (the `audit --new-formula` threw an error I think)… which is why I shoved it in my dotfiles for the time being, else I would have just submitted myself. Also they don't take too kindly to devs submitting their own stuff…

**Comment by mklement0** [comment]
Thanks - I had no idea; I've never submitted a formula before.

Wouldn't it make sense for devs to maintain their own formulas?

Re notability: Indeed, I just got this:

```na
GitHub repository not notable enough (<30 forks, <30 watchers and <75 stars)
```

Did you just want me to have the formula for eventual later submission, should it ever become notable enough?

Or do you see value in putting it under source control even now? So that users can install with something like:

```sh
brew install https://raw.githubusercontent.com/mklement0/fileicon/master/fileicon.rb
```

Since I always install it via `npm`, I'm trying to understand this use case better.

**Comment by danielbayley** [comment]
> Wouldn't it make sense for devs to maintain their own formulas?

> Did you just want me to have the formula for eventual later submission, should it ever become notable enough?

> do you see value in putting it under source control even now? So that users can install

@mklement0 Ideally it would live in [homebrew-core] so that it would be available with a simple `brew install fileicon`, but until it is deemed notable enough to be accepted, the formula should probably live somewhere in a _[tap]_… which basically means just putting it in a `Formula/` subfolder of a repository… that could be this one, the only stipulation is that the name of the repo has to have the `homebrew-` prefix to be able to do, for example:
~~~ sh
brew tap mklement0/fileicon # providing actual repo is renamed to homebrew-fileicon on GitHub.
brew install fileicon
~~~
else `brew install mklement0/fileicon/fileicon` without the rename, just pasting the above formula into `Formula/fileicon.rb`.

Also in a _[Brewfile]_:
~~~ rb
# Brewfile
tap 'mklement0/fileicon' # providing actual repo is renamed to homebrew-fileicon on GitHub.
brew 'fileicon'
# otherwise without the rename:
brew 'mklement0/fileicon/fileicon'
~~~

> Since I always install it via npm, I'm trying to understand this use case better.

I’m assuming that `node`/`npm` aren’t actually required at runtime since it’s essentially just a bash script… so making it available as a Homebrew formula is much more general purpose, and useful for  people who don’t use `node`/`npm` (not that I don’t… but to me a bash script should not depend on `npm` unnecessarily).

[homebrew-core]: https://github.com/Homebrew/homebrew-core
[tap]: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap
[brewfile]: https://github.com/Homebrew/homebrew-bundle#usage

**Comment by mklement0** [comment]
Thanks for the detailed info, @danielbayley.

Indeed, Node.js is not required at runtime - I simply used `npm` as a convenient cross-platform package manager and I'll stick with that for now.

**Comment by mklement0** [comment]
Thanks for the PR, @danielbayley.

I decided not to rename the repo, so people will have to use the following (I've updated the read-me):

```sh
brew install https://raw.githubusercontent.com/mklement0/fileicon/master/fileicon.rb
```

But hopefully that is still helpful.
