### ISSUE TITLE
v0.2.2 still on Homebrew, no 0.2.4

### ISSUE THREAD

**Issue by haakonstorm** [mklement0/fileicon#18]
<img width="762" alt="Screenshot of iTerm2 (05-01-2020, 23-49-16)" src="https://user-images.githubusercontent.com/193781/71787268-0c2e5c00-3016-11ea-9cb5-cf552edd16b2.png">

**Comment by mklement0** [comment]
Thanks, @haakonstorm. 

The versions are actually functionally identical, and the two patch-version updates only relate to introducing the Homebrew formula.

I'll sync them with the next update.
