### ISSUE TITLE
macOS Utility Not an issue

### ISSUE THREAD

**Issue by chris1111** [mklement0/fileicon#31]
Thanks for your great work 
There are many CLI's to change Icons in macOS but I can tell you that fileicon is the best and the most preformed
I integrated it into my App ☛ [Here Icon- Changer](https://github.com/chris1111/Icon-Changer)

**Comment by mklement0** [comment]
I'm glad to hear it, @chris1111, and I appreciate the nice feedback; I've added a link to your app to the read-me.
