### ISSUE TITLE
Cannot change system apps' icnons

### ISSUE THREAD

**Issue by underthestars-zhy** [mklement0/fileicon#36]
```bash
Cannot modify '/System/Applications/Calculator.app': you do not have write permissions.
```

**Comment by westwong0622** [comment]
new macOS has a base image which can't change, can't change system app icon now

**Comment by mklement0** [comment]
Thanks, @westwong0622. Indeed, even with `sudo` you cannot modify apps in `/System/Applications` - verified on macOS 12.5.1 (Monterey).
