### ISSUE TITLE
The GET command takes a very long time

### ISSUE THREAD

**Issue by D-E-N-E-B** [mklement0/fileicon#37]
Get a file or folder's custom icon takes a little over two minutes on my Mac Studio! What could be the problem?
(fileicon v0.3.1)

**Comment by mklement0** [comment]
That is very strange - I see it too on my M1 Macbook Pro, although it takes about 1 minute. I'll have to investigate.

**Comment by mklement0** [comment]
@D-E-N-E-B, I just tried again on macOS Ventura 13.1, and I don't see the problem anymore.
Do you still see it, and, if so, on what macOS version?

**Comment by mklement0** [comment]
@D-E-N-E-B, given that the problem no longer occurs in  13.1, I'm closing this.
