### ISSUE TITLE
Set Finder Dock Icon

### ISSUE THREAD

**Issue by TBytes404** [mklement0/fileicon#44]
Add option to set Finder Dock Icon.

manually:
```
cd /System/Library/CoreServices/Dock.app/Contents/Resources
mv CUSTOM_ICON ./finder.png
```
possibility:
```
fileicon set Finder CUSTOM_ICON
fileicon rm Finder
```

**Comment by mklement0** [comment]
Thanks for the suggestion, but the fundamental obstacle to implementing such a feature is that SIP (System Integrity Protection) would have to be disabled, right?
