### ISSUE TITLE
"fileicon get" takes 54 seconds!

### ISSUE THREAD

**Issue by steven-j-klein** [mklement0/fileicon#45]
I feel obligated to mention that I really appreciate fileicon! Thank you for creating it.

I've just installed it and did some testing to familiarize myself with how it works.

I tried all 4 functions. The first three were instant, but get took forever:
`rm`: 0.155 seconds
`set`: 0.730 seconds
`test`: 0.138 seconds
`get`: **54.629 seconds**

My environment:
hardware: Mac mini (2018), 3.6 GHz Quad-Core Intel Core i3, 8GB RAM
software: macOS Monterey 12.6.7

Using Activity Monitor, I saw awk go to 99% CPU usage while the process was running.

Here's how I verified the time delay in terminal:
```
% time fileicon get tst2         
Custom icon extracted to 'tst2.icns'.
fileicon get tst2  53.90s user 0.15s system 98% cpu 54.629 total
%
```
Any suggestions?

**Comment by mklement0** [comment]
I appreciate the nice feedback, @steven-j-klein.

I've just added the following to the read-me, which isn't good news, unfortunately:

> Unfortunately, a bug beyond `fileicon`'s control causes the `get` sub-command (for extracting an existing icon) to be excessively slow on macOS 12 (Monterey); this has been fixed in macOS 13 (Ventura).

In other words: Unfortunately, the only solution I know of is to upgrade to Ventura.
