### ISSUE TITLE
Looks like macOS 14.1 do not support set file icon on mobile hard disk ?

### ISSUE THREAD

**Issue by zanezhangzz** [mklement0/fileicon#46]
My mobile hard disk file system is ExFAT.   It is do not work even if set icon by mouse drag . Has anyone encountered such a problem?

**Comment by mklement0** [comment]
I don't have macOS 14 installed yet and no ExFAT drive to experiment with.

My understanding is that it _should_ work, and if it doesn't for you even with dragging then there's probably nothing `fileicon` can do. 

Did it work for you in macOS 13?

Perhaps [this AskDifferent post](https://apple.stackexchange.com/q/237337/28668) helps (though it long predates macOS 14).

**Comment by FantaZZ** [comment]
@mklement0  Yes, ```fileicon``` is works on macOS 13.  And I konw it is not a probem with ```fileicon```,  because of dragging also can not set icon. Just ask for anyone encountered such a problem.

Thanks for answer and link. 😊

**Comment by zanezhangzz** [comment]
@mklement0 Yes, fileicon is works on macOS 13. And I konw it is not a probem with fileicon, because of dragging also can not set icon. Just ask for anyone encountered such a problem.

Thanks for answer and link. 😊
